name: Release creator

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Load up PyScript version 
        id: ver
        run: echo "version=$(cat python-version.txt)" > $GITHUB_OUTPUT
      - name: Build
        run: |
            git checkout -b release || git checkout release
            git push --set-upstream origin release || git branch --set-upstream-to=origin/release release || true
            cd release || mkdir release && cd release
            mkdir pyscript
            cp ../pyscript/* pyscript/
            cp ../demo.html index.html
            cp ../ide.html ide.html
            cp ../hello.html repl.html
            cd ..
            mkdir build && cd build
            zip -r offline.zip ../release/
            rm -rf ../release/
            
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: build/offline.zip
          body: "Offline release with **IDE verhere** and **REPL verhere** (PyScript version: ${{ steps.ver.outputs.version }})!"
          
