name: Manually update Pyodide

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Pyodide version"
        required: true
        type: string
      update_version_file:
        description: "Update pyodide-version.txt?"
        required: true
        type: boolean
        default: true
      useapi:
        description: "Directly try GitHub API?"
        required: false
        type: boolean
        default: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check version exists
        run: |
          VERSION="${{ inputs.version }}"
          if ${{ inputs.useapi }}; then
            LINK="https://api.github.com/repos/pyodide/pyodide/releases/tags/$VERSION"
          else
            LINK="https://cdn.jsdelivr.net/pyodide/$VERSION/full/pyodide.js"
          fi
          curl -s "$LINK" >/dev/null
          if [ $? -eq 0 ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "Version $VERSION doesn't exist"
            exit 1
          fi
        id: check
      - name: Update pylock.json
        run: python3 ./pydate.py "v${{ steps.check.outputs.version }}"
      - name: Update version file
        if: ${{ inputs.update_version_file == 'true' }}
        run: echo "v${{ steps.check.outputs.version }}" > pyodide-version.txt
      - name: Commit and PR
        run: |
          git checkout -b pyodide-${{ steps.check.outputs.version }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Pyodide to ${{ steps.check.outputs.version }}"
          git push --force origin pyodide-${{ steps.check.outputs.version }}
      - name: Create PR
        uses: ws2git/gh-pr-creator-action@v1
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          title: "Update Pyodide to ${{ steps.check.outputs.version }}"
          body: "Manually triggered update to ${{ steps.check.outputs.version }}"
          source_branch: "pyodide-${{ steps.check.outputs.version }}"
          dest_branch: "main"
