name: Release from branch

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Essential
        id: ver
        run: |
          echo "version=$(cat python-version.txt)" > $GITHUB_OUTPUT
          git checkout release
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: build/offline.zip
          body: "Offline release with **IDE verhere** and **REPL verhere** (PyScript version: ${{ steps.ver.outputs.version }})!"
