name: Release from branch

on:
  workflow_dispatch:
  repository_dispatch:
    types: ["relnow"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Essential
        id: ver
        run: |
          git checkout -b release || git checkout release
          git push --set-upstream origin release || git branch --set-upstream-to=origin/release release || echo "$(git pull origin release && git push origin release)" || true
          echo "version=$(cat pyscript-version.txt)" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: build/offline.zip
          tag_name: ${{ steps.ver.outputs.version }}
          make_latest: "true"
          body: "Offline release with **IDE verhere** and **REPL verhere** (PyScript version: ${{ steps.ver.outputs.version }})!"
