name: Zip it shipit

on: 
  workflow_dispatch:
    inputs:
      i:
        description: 'IDE version'
        required: true
        type: string
      r:
        description: 'REPL version'
        required: true
        type: string
      m:
        description: 'MULTI version'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Brancher
        run: |
          git checkout -b release || git checkout release
          git push --set-upstream origin release || git branch --set-upstream-to=origin/release release || echo "$(git pull origin release && git push origin release)" || true
      - name: Zip it
        id: ver
        run: |
          mkdir build
          zip -r offline.zip release/
          mv offline.zip ./build/
          echo "version=$(cat pyscript-version.txt)" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: ./build/offline.zip
          tag_name: "i${{ inputs.i }}+r${{ inputs.r }}+m${{ inputs.m }}"
          make_latest: "true"
          body: "Offline release with **IDE v${{ inputs.i }}**, **REPL v${{ inputs.r }}** and **MULTI v${{ inputs.m }}** (PyScript version: ${{ steps.ver.outputs.version }})! For more info to use, visit [here](https://github.com/Ericwasepic127/ericwasepic127.github.io/wiki/Using-Py3REPL-or-Py3IDE-without-internet#2nd-way-by-offline-package---most-robust-option)."
